services:
  jaeger:
    image: jaegertracing/all-in-one:1.46
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  api-gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DEPLOYMENT_ENV=development
    depends_on:
      - jaeger
      - service-a
      - service-b

  service-a:
    build:
      context: .
      dockerfile: service_a/Dockerfile
    environment:
      - DEPLOYMENT_ENV=development
    depends_on:
      - jaeger

  service-b:
    build:
      context: .
      dockerfile: service_b/Dockerfile
    environment:
      - DEPLOYMENT_ENV=development
    depends_on:
      - jaeger
